version: 2.0
jobs:
  build:
    docker:
      - image: circleci/ruby:2.7.0
    steps:
      - checkout
      - run:
        name: bundle version
        command: bundle -v
      - run:
        name: bundle install
        command: bundle install
      - run:
        name: test rest
        command: ruby rest.rb
      - run:
        name: test scan
        command: ruby scan.rb
