version: 2.1
orbs:
  ruby: circleci/ruby@0.1.2

jobs:
  build:
    docker:
      - image: ubuntu:20.04
    steps:
      - checkout
      - run:
        name: Which bundler?
        command: bundle -v
      - ruby/bundle-install
      - ls

workflows:
  version: 2
  build_and_test:
    jobs:
      - build
      - test
