name: Ruby

on: [push]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2

      - name: Setup
        uses: actions/setup-ruby@v1
        with:
          ruby-version: 2.6.x

      - name: Install
        run: |
          gem install bundler
          bundle install --jobs 1 --retry 0

      - name: Lint
        run: rubocop
        
      - name: Build
        run: docker build . -t cve-api
